name: DC Photography Boston
favicon: null
layout_spectrum: 0.7823362585622817
typography_spectrum: 0.6905483698938042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.47338314773514867
  lightness: 0.12819915264844894
  saturation: 0.6250422063749284
  rhythmicContrast: 0.881965538021177
purpose: []
