name: DC Photography Boston
favicon: null
layout_spectrum: 0.91485
typography_spectrum: 0.34576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#01066e'
    - '#0000ff'
    - '#393c8e'
    - '#8a8cb1'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
