name: DC Photography Boston
favicon: null
layout_spectrum: 0.91485
typography_spectrum: 0.6905483698938042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#01066e'
    - '#0000ff'
    - '#393c8e'
    - '#8a8cb1'
  brandStrength: 1
  lightness: 0.12819915264844894
  saturation: 0.6250422063749284
  rhythmicContrast: 0.881965538021177
purpose: []
